### PR TITLE
Fix view for when user has been logged out

### LINKED ISSUE #67: Conflicting logged in status messages
Vivian reported: "I logged in and left the webapp for a while, I guess the webapp silently timed out my login (which is fine). But the Logged should not show that I am still logged in. "

Image

### PR DESCRIPTION
**Pull request by dnoneill**
closes #67 

https://github.com/user-attachments/assets/8cbc5ffd-4a2d-4590-b832-e093798e670a

### CODE REVIEW

File: app/controllers/authentication_controller.rb [hunk 1]
```diff
@@ -8,6 +8,7 @@ class AuthenticationController < ApplicationController
 
   def login
     start_new_session # Creates/updates user and set session cookie.
+    cookies.signed.permanent[:logged_in] = { httponly: true, same_site: :lax, expires: 7.hours.from_now }
```
Comment (edsu) [inline app/controllers/authentication_controller.rb]: Why are we using `permanent` here (20 years) and also `expires` set to 7 hours? Should it be `cookies.signed` instead of `cookies.signed.permanent`?

**Review by edsu — CHANGES_REQUESTED** [review]

File: app/controllers/authentication_controller.rb (hunk 1 above)
Comment (edsu) [reply app/controllers/authentication_controller.rb]: After reading the Rails docs it seems like this should work, and would read a bit better in my opinion:

```ruby
cookies.signed[:logged_in] = { httponly: true, same_site: :lax, expires: 7.hours.from_now }
```

File: app/javascript/controllers/check_login_controller.js
[the remark this answers is not in the document]
Comment (edsu) [reply app/javascript/controllers/check_login_controller.js]: Nice, thanks! I noticed a weird white line across the screen, but I don't think that's a huge issue?

Screenshot 2025-12-17 at 5 42 08 PM

File: app/controllers/downloads_controller.rb [hunk 2]
```diff
@@ -7,7 +7,12 @@ class DownloadsController < ApplicationController
   def index; end
 
   def download
-    authorize! to: :view?, with: RestrictedPolicy
+    return redirect_to download_path(session_timeout: true) unless current_user
+
+    unless business_access?
+      return render status: :unauthorized,
+                    json: { error: 'You are not authorized to access this file.' }
+    end
```
Comment (edsu) [inline app/controllers/downloads_controller.rb]: I'm confused why the `authorize!` call was replaced in favor of using `business_access?`.  Was it simply to change the JSON message?

**Review by edsu — APPROVED** [review]
I still had some questions, but am marking them approved since I don't think they need to be answered for this to move forward.

File: app/controllers/downloads_controller.rb (hunk 2 above)
Comment (dnoneill) [reply app/controllers/downloads_controller.rb]: authorize! will just auto-error. You can't redirect if you use authorize!
